# Generated by Django 3.0.6 on 2020-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(max_length=5000)),
                ('date', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
